tour_mvc_wind-main/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "registrations#new"
  resources :login, only: [:create]
  resources :registrations, only: [:create]
  delete :logout, to: "login#logout"
  get :logged_in, to: "login#logged_in"
  # get "home", to: "homepage#index"
  
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  # get "sign_in", to: "login#new"
  # post "sign_in", to: "login#create"
  post "logout", to: "login#logout"
  get "is_admin", to: "login#is_admin"

  get "add_tour", to: "tours#new"
  get "tours", to: "tours#showAllTour"
  get "chosen_tour", to: "tours#showTour"
  post "add_tour", to: "tours#create"
  post "tours_with_companion", to: "tours#bookTicketWithCompanion"
  post "tours_without_companion", to: "tours#bookTicketWithoutCompanion"
  
  
  get "tickets", to: "tickets#showUserTickets"
  get "all_tickets", to: "tickets#showAllTickets"
  post "cancel", to: "tickets#cancelTicket"

  get "admin", to: "admin#new"
  post "admin", to: "admin#create"
  post "logout_admin", to: "admin#logout"

end

tour_mvc_wind-main/app/controllers/login_controller.rb
class LoginController < ApplicationController
    before_action :set_current_user
    
    def set_current_user
        if session[:user_id].present?
            puts session[:user_id].to_s + " here"
            @current_user = User.find(session[:user_id])
        end
    end

    def create
        user = User.find_by(user_name: params[:user_name])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            render json: {
                status: :created,
                logged_in: true,
                user: user
            }, status: 200
        else
            # user_name or password not exists
            render json: { status: :not_logged_in }, status: 401
        end
    end

    def is_admin
        user = User.find_by(user_name: params[:user_name])
        if user.present? && user.is_admin
            render json:{
                is_admin: true
            }
        else
            render json:{
                is_admin: false
            }
        end
    end

    def logged_in
        if @current_user
            render json: {
                logged_in: true,
                user: @current_user
            }, status: 200
        else
            render json: {
                logged_in: false
            }, status: 401
        end
    end

    def logout
        reset_session
        session[:user_id] = nil
        render json: {
            status: 200,
            logged_out: true
        }, status: 200
    end
end

tour_mvc_wind-main/app/views/login/new.html.erb
<div class="ms-5 mt-5 me-5">
    <h1>Sign In</h1>
    <div class="text-center">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: 'alert alert-info' %>
      <% end %>
    </div>
    <%= form_with url: sign_in_path do |form|%>
        <div class="mb-3">
            <%= form.label :user_name %>
            <%= form.text_field :user_name, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= form.label :password %>
            <%= form.password_field :password, class: "form-control" %>
        </div>
        <div class="container mb-3">
            <div class="row row-cols-auto">
                <%= form.submit "LogIn", class: "btn btn-primary" %>
                <div class="mt-2" >
                    <h6 class="fs-6 fw-light ms-2">Don't have an account?</h6>
                </div>
                <%= link_to '<button type="button" class="btn btn-dark">Sign Up</button>'.html_safe, sign_up_path %>
            </div>
        </div>
    <% end %>
</div>