tour_mvc_wind-main/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "registrations#new"
  resources :login, only: [:create]
  resources :registrations, only: [:create]
  delete :logout, to: "login#logout"
  get :logged_in, to: "login#logged_in"
  # get "home", to: "homepage#index"
  
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  # get "sign_in", to: "login#new"
  # post "sign_in", to: "login#create"
  post "logout", to: "login#logout"
  get "is_admin", to: "login#is_admin"

  get "add_tour", to: "tours#new"
  get "tours", to: "tours#showAllTour"
  get "chosen_tour", to: "tours#showTour"
  post "add_tour", to: "tours#create"
  post "tours_with_companion", to: "tours#bookTicketWithCompanion"
  post "tours_without_companion", to: "tours#bookTicketWithoutCompanion"
  
  
  get "tickets", to: "tickets#showUserTickets"
  get "all_tickets", to: "tickets#showAllTickets"
  post "cancel", to: "tickets#cancelTicket"

  get "admin", to: "admin#new"
  post "admin", to: "admin#create"
  post "logout_admin", to: "admin#logout"

end

tour_mvc_wind-main/app/models/tour.rb
class Tour < ApplicationRecord
    has_many :tickets
    has_many :companions
    validates :tour_code, presence: true, uniqueness:true
    validates :from, presence: true
    validates :to, presence: true
    validates :start_time, presence: true
    validates :end_time, presence: true
    validates :passenger_limit, presence: true, numericality: { greater_than: 0 } 
    validates :price, presence: true, numericality: { greater_than: 0 } 
    validates :date, presence: true

    def bookTicketWithoutCompanion(user)
        if Ticket.find_by(user_id: user.id, tour_id: self.id).present?
            return {
                "status" => "already_booked",
                "ticket_created" => false
            }
        elsif self.passenger_limit == 0
            return {
                "status" => "completely_booked",
                "ticket_created" => false
            }
        else
            new_ticket = Ticket.new
            new_ticket.user_id = user.id
            new_ticket.tour_id = self.id

            new_ticket.save
            self.passenger_limit = self.passenger_limit - 1
            self.save
            return {
                "status" => "created",
                "ticket_created" => true
            }
        end
    end

    def bookTicketWithCompanion(user)

        if Ticket.exists?(user_id: user.id, tour_id: self.id)
            return {
                "status" => "already_booked",
                "ticket_created" => false
            }
        elsif self.passenger_limit == 0
            return {
                "status" => "completely_booked",
                "ticket_created" => false
            }
        else
            new_ticket = Ticket.new
            new_ticket.user_id = user.id
            new_ticket.tour_id = self.id

            if Companion.find_by(tour_id: self.id, gender: user.gender).present?
                companion_to_remove = Companion.find_by(tour_id: self.id, gender: user.gender)
                
                ticket_to_update = Ticket.find(companion_to_remove.ticket_id)
                ticket_to_update.companion_user_name = user.user_name
                ticket_to_update.save

                new_ticket.companion_user_name = User.find(companion_to_remove.user_id).user_name
                new_ticket.save
                companion_to_remove.delete
            else
                companion_to_add = Companion.new
                
                new_ticket.save
                
                companion_to_add.gender = user.gender
                companion_to_add.tour_id = self.id
                companion_to_add.user_id = user.id
                companion_to_add.ticket_id = new_ticket.id
                companion_to_add.save
            end
            self.passenger_limit = self.passenger_limit - 1
            self.save
            return {
                "status" => "created",
                "ticket_created" => true
            }
        end
    end
end

tour_mvc_wind-main/app/controllers/tours_controller.rb
class ToursController <  ApplicationController
    def create
        new_tour = Tour.new(tourParams)
        if new_tour.valid?
            new_tour.save
            render json: {
                status: :added_tour,
                tour_added: true
            }, status: 200
        else
            render json: { 
                status: :something_went_wrong,
                tour_added: false
            }, status: 422
        end
    end

    def showAllTour
        tours = Tour.all
        render json: TourSerializer.new(tours).serialized_json, status: 200
    end

    def showTour
        chosen_tour = Tour.find(params[:tour_id])
        render json: TourSerializer.new(chosen_tour).serialized_json, status: 200
    end

    def bookTicketWithoutCompanion
        if Tour.exists?(params[:param])
            tour_to_book = Tour.find(params[:param])
            user = User.find_by(user_name: params[:user_name])

            obtained_json = tour_to_book.bookTicketWithoutCompanion(user)
            render json: obtained_json, status: 200
        else
            render json:{
                status: :invalid_tour,
                ticket_created: false
            }, status: 404
        end
    end

    def bookTicketWithCompanion
        if Tour.exists?(params[:param])
            tour_to_book = Tour.find(params[:param])
            user = User.find_by(user_name: params[:user_name])

            obtained_json = tour_to_book.bookTicketWithCompanion(user)
            render json: obtained_json, status: 200
        else
            render json:{
                status: :invalid_tour,
                ticket_created: false
            }, status: 404
        end
    end

    private 
    def tourParams
        params.permit(:tour_code, :from, :to, :start_time, :end_time, :passenger_limit, :price, :date)
    end
end

tour_mvc_wind-main/app/views/tours/new.html.erb
<%= render partial: "shared/navbar"%>
<div class="text-center">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: 'alert alert-info' %>
      <% end %>
</div>
<div class="ms-5 mt-5 me-5">
    <h2> Add a tour </h2>
    <%= form_with url: add_tour_path do |form|%>
        <div class="mb-3">
            <%= form.label :tour_code %>
            <%= form.text_field :tour_code, class: "form-control" %>
        </div>
        <div class="input-group mb-3">
            <div class="col-md-5">
                <%= form.label :from %>
                <%= form.text_field :from, class: "form-control" %>
            </div>
            <div class="col-md-2">
            </div>
            <div class="col-md-5">
                <%= form.label :to %>
                <%= form.text_field :to, class: "form-control" %>
            </div>
        </div>
        <div class="input-group mb-3">
            <div class="col-md-5">
                <%= form.label :start_time %>
                <%= form.time_field :start_time, class: "form-control" %>
            </div>
            <div class="col-md-2">
            </div>
            <div class="col-md-5">
                <%= form.label :end_time %>
                <%= form.time_field :end_time, class: "form-control" %>
            </div>
        </div>
        <div class="input-group mb-3">
            <div class="col-md-5">
                <%= form.label :passenger_limit %>
                <%= form.number_field :passenger_limit, min: 1,  class: "form-control" %>
            </div>
            <div class="col-md-2">
            </div>
            <div class="col-md-5">
                <%= form.label :price %>
                <%= form.number_field :price, min: 1, class: "form-control" %>
            </div>
        </div>
        <div class="mb-3">
            <%= form.label :date %>
            <%= form.date_field :date, class: "form-control" %>
        </div>
        <%= form.submit "Add", class: "btn btn-primary" %>
    <% end %>
</div>

tour_mvc_wind-main/app/views/tours/showTour.html.erb
<%= render partial: "shared/navbar"%>
<div class="text-center">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: 'alert alert-info' %>
      <% end %>
</div>

<div class="ms-5 mt-5 me-5">
    <h1> Tour </h1>
    <table class="table table-striped">
        <tr>
            <th>Tour Code</th>
            <th>From </th>
            <th>To </th>
            <th>Date</th>
            <th>Price</th>
        </tr>
        <tr>
            <td><%= @chosen_tour.tour_code %></td>
            <td><%= @chosen_tour.from %></td>
            <td><%= @chosen_tour.to %></td>
            <td><%= @chosen_tour.date.strftime('%A, %d/%m/%Y') %></td>
            <td><%= @chosen_tour.price %></td>
        </tr>
    </table>
    <div class="container mb-3">
            <div class="row row-cols-auto">
                <%= button_to 'Book with Companion', tours_with_companion_path(param:@chosen_tour.id), class: "btn btn-primary" %>
                <%= button_to 'Book without Companion', tours_without_companion_path(param:@chosen_tour.id), class: "btn btn-warning" %>
            </div>
    </div>
</div>

tour_mvc_wind-main/app/views/tours/show_all.html.erb
<%= render partial: "shared/navbar"%>
<div class="text-center">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: 'alert alert-info' %>
      <% end %>
</div>
<div class="ms-5 mt-5 me-5">
    <h1> Tour List </h1>
    <table class="table table-striped">
    <tr>
        <th>Tour Code</th>
        <th>From </th>
        <th>To </th>
        <th>Date</th>
        <th>Price</th>
        <th>Status</th>
    </tr>

    <% @tours.each do |tour| %>
        <tr>
            <td><%= tour.tour_code %></td>
            <td><%= tour.from %></td>
            <td><%= tour.to %></td>
            <td><%= tour.date.strftime('%A, %d/%m/%Y') %></td>
            <td><%= tour.price %></td>
            <td><%= @tickets.find_by(user_id: session[:user_id], tour_id: tour.id).present? ? "Already booked" : (link_to '<button type="button" class="btn btn-secondary">Book</button>'.html_safe, chosen_tour_path(param:tour)) %> </td>
        </tr>
    <% end %>
    </table>
</div>