tour_mvc_wind-main/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "registrations#new"
  resources :login, only: [:create]
  resources :registrations, only: [:create]
  delete :logout, to: "login#logout"
  get :logged_in, to: "login#logged_in"
  # get "home", to: "homepage#index"
  
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  # get "sign_in", to: "login#new"
  # post "sign_in", to: "login#create"
  post "logout", to: "login#logout"
  get "is_admin", to: "login#is_admin"

  get "add_tour", to: "tours#new"
  get "tours", to: "tours#showAllTour"
  get "chosen_tour", to: "tours#showTour"
  post "add_tour", to: "tours#create"
  post "tours_with_companion", to: "tours#bookTicketWithCompanion"
  post "tours_without_companion", to: "tours#bookTicketWithoutCompanion"
  
  
  get "tickets", to: "tickets#showUserTickets"
  get "all_tickets", to: "tickets#showAllTickets"
  post "cancel", to: "tickets#cancelTicket"

  get "admin", to: "admin#new"
  post "admin", to: "admin#create"
  post "logout_admin", to: "admin#logout"

end

tour_mvc_wind-main/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
        <img src="https://img.icons8.com/emoji/2x/waving-hand-light-skin-tone.png" alt="Welcome Image" width="30" height="24" class="d-inline-block align-text-top">
    </a>
    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Book Tour", tours_path, class: "nav-link", method: :get %>
        </li>
        <li class="nav-item">
          <%= link_to 'My Tickets',  tickets_path, class: "nav-link", method: :get %>
        </li>
        <li class="nav-item">
          <%= @user.is_admin ? ( link_to 'See All Ticket',  all_tickets_path, class: "nav-link" ) : "" %>
        </li>
        <li class="nav-item">
          <%= @user.is_admin ? ( link_to 'Add Tour',  add_tour_path, class: "nav-link" ) : "" %>
        </li>
      </ul>
    </div>
    <div id="navbarNav">
        <ul class="navbar-nav justify-content-end collapse navbar-collapse">
            <li class="nav-item">
                <div class= "nav-link" data-toggle="tooltip" data-html="true" title= "User Id => <%= @user.id.to_s %> and gender => <%= @user.gender.eql?("m") ? "Male": "Female" %>" >
                    Welcome <%= @user.user_name %>
                </div>
            </li>
            <li class="nav-item">
            <%= @user.is_admin ? (button_to 'Log Out',  logout_admin_path, method: :post) : (button_to 'Log Out',  logout_path, method: :post) %>
            </li>
        </ul>
    </div> 
  </div>
</nav>