tour_mvc_wind-main/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "registrations#new"
  resources :login, only: [:create]
  resources :registrations, only: [:create]
  delete :logout, to: "login#logout"
  get :logged_in, to: "login#logged_in"
  # get "home", to: "homepage#index"
  
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  # get "sign_in", to: "login#new"
  # post "sign_in", to: "login#create"
  post "logout", to: "login#logout"
  get "is_admin", to: "login#is_admin"

  get "add_tour", to: "tours#new"
  get "tours", to: "tours#showAllTour"
  get "chosen_tour", to: "tours#showTour"
  post "add_tour", to: "tours#create"
  post "tours_with_companion", to: "tours#bookTicketWithCompanion"
  post "tours_without_companion", to: "tours#bookTicketWithoutCompanion"
  
  
  get "tickets", to: "tickets#showUserTickets"
  get "all_tickets", to: "tickets#showAllTickets"
  post "cancel", to: "tickets#cancelTicket"

  get "admin", to: "admin#new"
  post "admin", to: "admin#create"
  post "logout_admin", to: "admin#logout"

end

tour_mvc_wind-main/app/views/admin/new.html.erb
<div class="ms-5 mt-5 me-5">
    <h1>Sign In</h1>
    <div class="text-center">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: 'alert alert-info' %>
      <% end %>
    </div>
    <%= form_with url: admin_path do |form|%>
        <div class="mb-3">
            <%= form.label :user_name %>
            <%= form.text_field :user_name, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= form.label :password %>
            <%= form.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= form.submit "LogIn", class: "btn btn-primary" %>
        </div>
    <% end %>
</div>